#!/bin/sh

if [ "$(id -u)" != "0" ]; then
	echo "ERROR: This script must be run as root" 1>&2
	exit 1
fi

yum install -y epel-release
yum install -y https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
yum install -y httpd httpd-tools php php-mysql php-pear php-gd php-mbstring php-mcrypt php-curl mysql-community-server php-mysql git

rm -Rf /var/www/html
git clone https://github.com/webpwnized/mutillidae.git /var/www/html

sed -i "s/127\.0\.0\.1/localhost/g" /var/www/html/includes/database-config.inc
chown -R apache:apache /var/www/html/*

systemctl enable httpd
systemctl start httpd

systemctl enable mysqld
systemctl start mysqld

OLD_PWD=$(grep 'A temporary password' /var/log/mysqld.log | tail -1 | awk '{print $NF}')
NEW_PWD="mutillidae"
mysql -uroot -p${OLD_PWD} --connect-expired-password -se "SET GLOBAL validate_password_policy=LOW; ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '"${NEW_PWD}"'; FLUSH PRIVILEGES;"
